### ISSUE TITLE
中国地图资源来源问题

### ISSUE THREAD

**Issue by ghost** [echarts-maps/echarts-china-provinces-js#4]
请问echarts-china-provinces-js地图是来源于中国国土资源部公开发表的版本吗？具体来源于哪个版本呢？

**Comment by chfw** [comment]
This bundling code is MIT license The echarts maps are included here under BSD-3 license of Baidu Inc.

**Comment by chfw** [comment]
echarts-china-provinces-js地图不是来源于中国国土资源部公开发表的版本！

中国国土资源部需要进行每个用法的审查，所以大家可以自己前去报备，然后用本站的工具自己制作。
